version: '3'
services:
    userservice-app:
        container_name: userservice-app
        image: catalinpatularu/userservice
        restart: on-failure
        ports: 
            - 10555:9091
        environment: 
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - carsurfing-mysql
    carsurfing-mysql:
        container_name: carsurfing-mysql
        image: mysql
        restart: always
        environment: 
            MYSQL_DATABASE: carsurfing
            MYSQL_ROOT_PASSWORD: test1234
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - ./mysql-data:/var/lib/mysql
        ports:
            - 6666:3306
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=test1234 --execute \"SHOW DATABASES \""
            interval: 4s
            timeout: 20s
            retries: 5
        