version: '3'
services:
    rideservice-app:
        container_name: rideservice-app
        image: rideservice
        restart: on-failure
        ports:
            - 9091:9091
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - carsurfing-mysql
    userservice-app:
        container_name: userservice-app
        image: userservice
        restart: on-failure
        ports:
            - 9092:9092
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - carsurfing-mysql
    reviewservice-app:
        container_name: reviewservice-app
        image: reviewservice
        restart: on-failure
        ports:
            - 9099:9099
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - carsurfing-mysql
            - userservice-app
    carsurfing-mysql:
        container_name: carsurfing-mysql
        image: carsurfing-mysql
        restart: always
        environment:
            MYSQL_DATABASE: carsurfing
            MYSQL_ROOT_PASSWORD: test1234
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - ./mysql-data:/var/lib/mysql
        ports:
            - 6666:3306
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=test1234 --execute \"SHOW DATABASES \""
            interval: 4s
            timeout: 20s
            retries: 5
